env:
  GITHUB_TOKEN: ENCRYPTED[58ec8880be6b3188bc31f0c711e724eabb8d4df0a32d1c0d5d1c43945e1cd92c59fda2d074e4c5d280cd7627f43c97b5]

publish_task:
  container:
    dockerfile: Dockerfile
  script:
    - date > stamp.txt
    - ./ci/publish.sh

  stamp_artifacts:
    path: stamp.txt
