test_task:
  container:
    dockerfile: Dockerfile
    docker_arguments:
      matrix:
        - zeek_flavor: zeek
        - zeek_flavor: zeek-lts

  test_script:
    - which clang++-10
    - ls /opt/zeek
