env:
  GITHUB_TOKEN: ENCRYPTED[58ec8880be6b3188bc31f0c711e724eabb8d4df0a32d1c0d5d1c43945e1cd92c59fda2d074e4c5d280cd7627f43c97b5]
  HOMEBREW_BOTTLE_DOMAIN: https://ghcr.io/v2/homebrew/core

publish_task:
  container:
    dockerfile: Dockerfile
  script:
    - date > stamp.txt
    - ./ci/publish.sh

  stamp_artifacts:
    path: stamp.txt

macos_task:
  osx_instance:
    image: catalina-base

  homebrew_script:
    - brew install bison flex cmake ninja python@3.8 sphinx-doc doxygen ccache zeek
