name: Run tests on Docker image

on: [push]

jobs:
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Compute target tag
        id: target
        run: |
          echo "::set-output name=tag::foo/bar"

      - name: Conditional
        if: steps.target.outputs.tag != ''
        run: echo "foo"
