
name: Run tests on Docker image

on: [push]

env:
  TEST_TAG: zeek:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump env
        env:
          REF: ${{ github.event.push.ref }}
        run: |
          echo $REF
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Build container
        uses: docker/build-push-action@v2.7.0
        id: build_container
        with:
          context: .
          file: Dockerfile
          load: true
      - name: Run tests
        uses: plexsystems/container-structure-test-action@v0.2.0
        with:
            image: ${{ env.TEST_TAG }}
            config: container-structure-test.yaml
