name: Run tests on Docker image

on: [push]

jobs:
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          context: ./
          file: Dockerfile
          load: true
          tags: FOO

      - uses: docker/build-push-action@v2
        with:
          context:  ./
          file: Dockerfile
          tags: BAR
